VideoQuickStart.xcodeproj/project.pbxproj
VideoQuickStart/Assets.xcassets/AppIcon.appiconset/Contents.json
VideoQuickStart/ViewController.swift

Should allow one-step installation via `pod install`, or by dragging/dropping .framework files into the Xcode project.

Installation method agnostic

---

README.md

The other option would be to suggest that all developers just run `pod update` but that requires the main spec repo to be updated each time. If you run `pod install` but you've never fetched Twilio's repo before you will get a fresh copy.

Clarify Cocoapods installation steps in the README.

---

.gitignore
Podfile
VideoCallKitQuickStart.xcodeproj/project.pbxproj
VideoCallKitQuickStart.xcodeproj/project.xcworkspace/contents.xcworkspacedata
VideoCallKitQuickStart/AppDelegate.swift
VideoCallKitQuickStart/Assets.xcassets/AppIcon.appiconset/Contents.json
VideoCallKitQuickStart/Assets.xcassets/Contents.json
VideoCallKitQuickStart/Base.lproj/LaunchScreen.storyboard
VideoCallKitQuickStart/Base.lproj/Main.storyboard
VideoCallKitQuickStart/Info.plist
VideoCallKitQuickStart/Utils.swift
VideoCallKitQuickStart/ViewController+CallKit.swift
VideoCallKitQuickStart/ViewController+SimulateIncomingCall.swift
VideoCallKitQuickStart/ViewController.swift

Using CallKit APIs on Video Quickstart app.

Using CallKit APIs on Video Quickstart app.

---

VideoCallKitQuickStart/ViewController+CallKit.swift
VideoCallKitQuickStart/ViewController.swift

This PR has following changes -
1. StartCall - Avoid updating call.
2. Report `Connected` Call state to CallKit for outgoing call.
3. Disconnect from the Room on `providerDidReset` callback.
4. Following speakerbox's guidelines to configure audio session while simulating incoming call

CallKit QuickStart sample app improvements

---

CustomScreenCapturerExample/ExampleScreenCapturer.swift
Podfile
VideoQuickStart/ViewController.swift

- Uses 1.0.0-beta5
- Removed the audio route work around as Video SDK version 1.0.0-beta5 correctly chooses `TVIAudioOutputVideoChatDefault`  by default

Using TwilioVideo 1.0.0-beta5

---

Podfile
VideoCallKitQuickStart/ViewController+CallKit.swift
VideoCallKitQuickStart/ViewController.swift
VideoQuickStart/ViewController.swift

In 1.0.0-beta9,  to connect to a Room, TVIVideoClient instance is not required. You can connect to a Room using the class method.

1.0.0-beta9

---

Podfile
ScreenCapturerExample/ViewController.swift
VideoCallKitQuickStart/Base.lproj/Main.storyboard
VideoCallKitQuickStart/ViewController.swift
VideoQuickStart/Base.lproj/Main.storyboard
VideoQuickStart/ViewController.swift

In 1.0.0-beta We have replaced TVIVideoViewRenderer by TVIVideoView. This PR addresses changes in swift quickstart apps to use the new TVIVideoView APIs

Using 1.0.0 beta14

---

VideoCallKitQuickStart/ViewController.swift

Don’t forget to invalidate CXProvider, thanks Apple!

Invalidate CXProvider in deinit

---

VideoCallKitQuickStart/ViewController.swift
VideoQuickStart/ViewController.swift

When developers start by creating a token in the [Twilio console](https://www.twilio.com/console/video/runtime/testing-tools) and specify a room name when generating a token the default capitalization on the page is lower case while in this app it's upper case which can lead to confusion when getting started since room names are case sensitive

Set room text field to lower case by default

---

ScreenCapturerExample/ExampleScreenCapturer.swift

Fixed a bug in TVIScreenCapturer and in the software video pipeline where RGB CVPixelBuffer formats were incorrectly assumed to use host ordering (little endian on Ax ARM-based CPUs) instead of their in memory

Tagging the pixel buffer with the correct frame format

---

README.md

Update to use the direct 2.0.0-preview2 link since we don't pin these preview releases to latest.

Link to the 2.0.0-preview2 docs in the README.

---

Podfile
README.md

No breaking API changes in areas covered by the examples, since stats is not covered.

Consume 2.0.0-preview4.

---

AudioSinkExample/ViewController.swift
DataTrackExample.xcodeproj/project.pbxproj
DataTrackExample/ViewController.swift
Podfile
ScreenCapturerExample.xcodeproj/project.pbxproj
VideoCallKitQuickStart/ViewController+CallKit.swift
VideoCallKitQuickStart/ViewController.swift
VideoQuickStart.xcodeproj/project.pbxproj
VideoQuickStart/ViewController.swift

Consuming TwilioVideo 2.0.0-preview8 -
1. Callkit sample app uses new `TVIDefaultAudioDevice`
2. Basic Quickstart logs error when subscription error occurs.
3. Deprecated 8.1 support.

Consuming 2.0.0 preview8

---

README.md

Update README.md to reference 2.0.0-beta.
I have cut a new 1.x branch (based on master) where the QS examples using our 1.x GA APIs will live. This PR updates the README to crosslink back to 2.0-beta examples on master.
This should not be merged until after: https://github.com/twilio/video-quickstart-swift/pull/222 and one more PR to merge `2.0.0-preview` into master.

Merge master to 1.x.

---

.gitignore
AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m
AudioDeviceExample/AudioDevices/ExampleCoreAudioDevice.m
AudioDeviceExample/README.md
AudioDeviceExample/ViewController.swift
DataTrackExample/Info.plist
Podfile
README.md

This PR adds support for the API changes in 2.0.0-beta3, focusing on TVIAudioDevice and backgrounding. The devices in AudioDeviceExample have been updated to signal AVAudioSession state changes. I also updated the READMEs, and Podspec.
Right now, our examples are "static" in their usage of AVAudioSession and they typically just activate it at initialization time (`ExampleAVAudioEngineDevice`) or when the first format is read (`ExampleCoreAudioDevice`). 
I followed the convention from @piyushtank's original commit, by firing audio session events after starting/stopping the AudioUnit. I think we should reconsider this approach and tie the events purely to AVAudioSession interruptions, and manually activating / deactivating the AVAudioSession. This would make the code easier to read, and a …

ISDK-1912: Support TVIAudioDevice backgrounding (2.0.0-beta3)

---

ARKitExample/ViewController.swift
Podfile
README.md
ScreenCapturerExample/ExampleScreenCapturer.swift

Update our example apps for the 2.0.0 APIs. Since we don't reuse TVIVideoView this means that the changes were limited to TVIVideoFrame initialization.
I also updated the README.md and Podfile while I was at it.

ISDK-1989: Update for 2.0.0 APIs

---

DataTrackExample/ViewController.swift

This is similar to the fix made in our internal demo app, but hopefully a little more Swifty. In some cases, its not possible to cast the parsed JSON payload's members directly to a Float. See the ticket and internal PR for more info.

ISDK-1995: Fix parsing crash in DataTrackExample.

---

ScreenCapturerExample/README.md

Includes a deprecation notice for `TVIScreenCapturer`.
I did not mention the deprecation in the master `README.md`. Should I? Clicking on the project link will now take you to the new `README.md` with the notice.

ISDK-2197: Add a README.md for ScreenCapturerExample.

---

ReplayKitExample/README.md
ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift
ReplayKitExample/ReplayKitExample/ViewController.swift

This PR addresses some of the betterments identified in the original example [PR](https://github.com/twilio/video-quickstart-swift/pull/287).
We now preallocate and reuse the scaling buffers need for the `vImageScale` methods. This reduces our transient memory allocations. At the same time I noticed a bug where  we were holding on to the Room (and thus capturer) after disconnecting without an error.
**Before: Temporary vImage allocations**
**After: Only CVPixelBuffer allocations**

ISDK-2223: ReplayKit: Preallocate scaling buffers, fix leak.

---

VideoCallKitQuickStart/ViewController.swift

A customer reported an [issue](https://github.com/twilio/twilio-video-ios/issues/29) where the signaling connection timed out while in a room and on the CallKit UI from the lock screen and the CallKit UI never informed the user of the error.
Looking at the code, we were alerting CallKit that we were ending the call when it was initiated by the user, but were never doing anything if the call was ended from the server.
We now maintain a bit of state that lets us know if the user initiated the disconnect, and if not, we inform CallKit that the call has failed.

ISDK-2261: Properly handle non-user initiated room disconnections.

---

Podfile
ReplayKitExample/BroadcastExtension/SampleHandler.swift
ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift
ReplayKitExample/ReplayKitExample/ViewController.swift

This PR uses the `TVIVideoSource` APIs which will be part of the upcoming `2.6.0` release.
WIP

ISDK-2255: Use TVIVideoSource in the ReplayKitExample

---

ARKitExample/ViewController.swift
Podfile
README.md

This PR has - 
- ARKit example uses VideoSource APIs
- Podfile updated to use 2.6
- README changes

ISDK-2258 ARKit Example uses VideoSource APIs

---

VideoCallKitQuickStart/ViewController+CallKit.swift
VideoCallKitQuickStart/ViewController.swift

As reported in #351, the mute/unmute indicators between the CallKit UI and the AppUI were not always properly in sync. If muting/unmuting were performed from the CallKit UI, the AppUI would show the correct state on the button. However, if muting/unmuting from the AppUI, the CallKit UI would not be updated.
The issue was that we were never alerting the CallKitProvider about the change in mute status, which was an oversight. Now when the AppUI mute/button is pressed, a `CXSetMutedCallAction` object is created, wrapped in a `CXTransaction ` and is given to the `CXCallController` to perform. This will then invoke the same `provier:performSetMutedCallAction:` method that pressing the mute button from the CallKitUI does. This then calls the actual logic in the view controller to mute the local …

Fix issue where CallKit mute states are out of sync between CallKit UI and App UI

---

ARKitExample/ViewController.swift
AudioDeviceExample/ViewController.swift
AudioSinkExample/ViewController.swift
DataTrackExample/ViewController.swift
Podfile
ReplayKitExample/BroadcastExtension/SampleHandler.swift
ReplayKitExample/ReplayKitExample/ViewController.swift
VideoCallKitQuickStart/ViewController.swift
VideoQuickStart/ViewController.swift

This PR implements the reconnecting state callbacks `TVIRoomDelegate room(_ room: TVIRoom, isReconnectingWithError error: Error?)` and `TVIRoomDelegate didReconnect(to room: TVIRoom)` and picks up the 2.7 release. Also fixes a typo and consistently logs to the console in the `logMessage(messageText:)` method.

ISDK-2356: Implement reconnecting state callbacks

---

AudioSinkExample/ViewController.swift

In AudioSinkExample, once you are connected to a Room it is valid to begin recognizing your own Participant. Similarly, reconnecting doesn't impact the ability for AudioSink to vend samples from your own LocalAudioTrack.

ISDK-2386: Update check for Room.state in AudioSinkExample.

---

Podfile
ReplayKitExample/BroadcastExtension/SampleHandler.swift
ReplayKitExample/README.md
ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift

This PR updates ReplayKitExample to use the new `ConnectOptionsBuilder.isAutomaticSubscriptionEnabled` API (2.10.0).
* Update Podfile for 2.10
* Update SampleHandler to use `builder.isAutomaticSubscriptionEnabled = false`
* Increase maximum dimension from 640 -> 960. The extension has more predictable memory usage now
* Wait for Room disconnection when ending a broadcast
* Update README.md content
I was able to validate the changes in Xcode by connecting several Participants sharing audio + video. All this time my extension continued to consume negligible downstream bandwidth and memory usage remained flat.

ISDK-2455: Update ReplayKitExample for subscription APIs (2.10.0)

---

VideoCallKitQuickStart/ViewController.swift

CallKitQS was accessing UIKit in background thread in CallKit Action was causing the crash.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

ISDK-2470 - CallKitQS was accessing UIKit in background thread in CallKit Action

---

VideoCallKitQuickStart/ViewController.swift

Fixed bug in CallKit app to set supported handle type fixed the bug.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

ISDK-2508 - Fixed bug in CallKit app to open the app upon pressing the video button

---

AVPlayerExample/ViewController.m
MultiPartyExample/MainViewController.swift
MultiPartyExample/MultiPartyViewController.swift
ObjCVideoQuickstart/ViewController.m
Podfile
README.md
ReplayKitExample/BroadcastExtension/SampleHandler.swift
ReplayKitExample/ReplayKitExample/ViewController.swift
Utils/SettingsTableViewController.swift

This PR updates the Quickstarts for the `3.0.0-beta2` API changes:
- `TwilioVideoSDK.version` => `TwilioVideoSDK.sdkVersion`
- Updates for the renaming of the `TVIRemoteParticipantDelegate` methods
- Updates `Podfile` and `README.md` for `3.0.0-beta2`

ISDK-2555: Update Quickstart for 3.0.0-beta2

---

VideoCallKitQuickStart/Base.lproj/Main.storyboard
VideoCallKitQuickStart/ViewController+SimulateIncomingCall.swift
VideoCallKitQuickStart/ViewController.swift

This PR makes simulation of incoming calls in VideoCallKitQuickstart more powerful by adopting the [UserNotifications](https://developer.apple.com/documentation/usernotifications) framework. This allows the following inbound scenarios to be tested:
1. Application is active.
2. Application is inactive and foregrounded.
3. Application is background.
An accept/decline UI is presented. The accept action does not require foregrounding the app, allowing it to be delivered in the background. The default action foregrounds the app.

ISDK-2169, ISDK-2653: Simulate incoming CallKit calls in the background

---

README.md
ReplayKitExample/README.md

Add a cross-link to the iOS 13 migration guide in the opening notice, and in the **More Documentation** section. This PR is for master, for 3.0.0-beta see https://github.com/twilio/video-quickstart-ios/pull/421.

ISDK-2659: Cross link to iOS 13 migration guide (master)

---

ReplayKitExample/README.md

Tested ReplayKit on iOS 13.0 GM and confirmed that the bugs from beta8 are still present.

Confirm ReplayKit bugs on iOS 13.0 GM. (3.0)

---

README.md

Using CocoaPods 1.7.5 resolves duplicate category definition warnings, which sometimes cause prefix header compilation to fail. For example when using CocoaPods 1.5.3 with Xcode 11:
[Build target AudioDeviceExample_2019-09-19T13-13-02.txt](https://github.com/twilio/video-quickstart-ios/files/3633866/Build.target.AudioDeviceExample_2019-09-19T13-13-02.txt)
Earlier versions of CocoaPods define both `HEADER_SEARCH_PATHS` and `FRAMEWORK_SEARCH_PATHS` for TwilioVideo.framework causing the duplicates to be found in AudioDeviceExample, and other targets that use a Swift bridging header.

ISDK-2656: Recommend CocoaPods 1.7.5 or newer.

---

ARKitExample/Info.plist
AVPlayerExample/Info.plist
AudioDeviceExample/Info.plist
AudioSinkExample/Info.plist
DataTrackExample/Info.plist
MultiPartyExample/Info.plist
ObjCVideoQuickstart/Info.plist
ReplayKitExample/ReplayKitExample/Info.plist
ScreenCapturerExample/Info.plist
VideoCallKitQuickStart/Info.plist
VideoQuickStart/Info.plist

Presently the QuickStart apps don't behave well when run on an iOS 13 device in Dark Mode. This is a temporary measure to ensure the apps behave as expected until we have a chance to better support Dark Mode in the apps.

ISDK-2679: Temporarily enforce Light mode

---

ARKitExample/README.md
AVPlayerExample/README.md
README.md

Updates the `1.x` branch docs with a note about `3.0` and fixed a couple links to point to the `README.md` in the `1.x` branch for consistency.

ISDK-2603: Update 1.x docs to reference the 3.0 docs and fix some links

---

VideoCallKitQuickStart/ViewController.swift
VideoQuickStart/ViewController.swift

This PR addresses https://github.com/twilio/video-quickstart-ios/issues/384, where a RemoteVideoTrack might not be rendered. The specific sequence of events that is problematic is when unsubscribing to the old VideoTrack happens after the new VideoTrack is subscribed.
As I looked more closely at the code there were other issues (like some RemoteParticipants not having a delegate). I tried to make the event handling dynamic and flexible so that any time there is remote video to render, the example will attempt to render it instead of sitting idle.

ISDK-2749: VideoTracks might not be rendered in QS example.

---

AVPlayerExample/ViewController.m
AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m
AudioDeviceExample/ViewController.swift
AudioSinkExample/ViewController.swift
MultiPartyExample/MultiPartyViewController.swift
ObjCVideoQuickstart/ViewController.m
VideoCallKitQuickStart/ViewController+CallKit.swift
VideoCallKitQuickStart/ViewController.swift
VideoQuickStart/ViewController.swift

Our ViewControllers were leaking camera resources if the ViewController is used in a multi-view app (e.g. navigation or tab). Added camera cleanup into the ViewController's destruction path to avoid the leaks.

ISDK-2770 - Added camera cleanup in ViewController's cleanup path

---

.github/ISSUE_TEMPLATE.md

Added a snippet to show how to enable debug logging in the issue template.

ISDK-2800: Add debug level logging snippet.

---

AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m

This pull request fixes the bug reported by https://github.com/twilio/video-quickstart-ios/issues/456 ticket.
When an iPhone is connected to Airpod pro (or any other BT device) `ExampleAVAudioEngineDevice`, and when format change occurs, audio device was not applying the new format on the record and playout `AVAudioEngine`s. As a result, on BT device the audio was playing distorted.
Apparently there is no way to apply format changes on AVAudioEngine while its running - you will have to tear down and set up the AVAudioEngine again.
To fix the problem, the PR checks in `startRendering` and `startCapturing` callbacks - if the active audio format doesn't match with AVAudioEngine's audio format than teardown and setup the AVAudioEngine again, otherwise just restart the audio engine.
1. …

CLIENT-7473 AudioEngine example does not play music on air pod pro

---

Cartfile
Podfile

Update the Quickstart dependency managers to consume TwilioVideo iOS `3.4.0`.

Consume iOS 3.4.0

---

AudioDeviceExample/ViewController.swift
VideoQuickStart/SceneDelegate.swift
VideoQuickStart/ViewController.swift

This PR fixes a few issues in the Quickstarts that were found when testing with Xcode 12 Beta 2 and iOS 14 Beta 2
1. The CameraSource was not being shutdown properly when switching audio devices in the Audio Device Example app
2. The SceneDelegate in the VideoQuickstart was not being compiled under Xcode 12. Tweaked the Macro used to skip the file with Xcode 10.

ISDK-2938: Ensure Quickstart apps work when built with Xcode 12 and run on iOS 14

---

Podfile

Update to consume the `2.12.0` release of the iOS SDK.

Consume 2.12.0

---

README.md

Document that the quickstarts require the `Client-side Room Creation` setting enabled.

ISDK-3059: Add text about the requirement for Client-side Room Creation enabled.

---

AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.h
AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m

This Pull Request adds functionality in ExampleAVAudioEngineAudioDevice to play continuous music before connecting to a Room, while in a Room, or after disconnect. The PR adds two APIs in ExampleAVAudioEngineAudioDevice which can be used to start and stop the continuous music using the core audio. The ExampleAVAudioEngineAudioDevice uses `continuousMusic` flag to determine if it should continue playing music or not.
To play continuous music, the PR establishes the core audio upon continuousMusic request is received by ExampleAVAudioEngineAudioDevice.
While validating the audio route change, I ran into the following 100% reproducible error when call is not connected to the Room and music is being played by the same core audio -
```
02-02 22:47:43.653057-0800 …
```

ISDK-3191 - Play continuous music before-during-and-after the call

---

ARKitExample.xcodeproj/project.pbxproj
AVPlayerExample.xcodeproj/project.pbxproj
AudioDeviceExample.xcodeproj/project.pbxproj
AudioSinkExample.xcodeproj/project.pbxproj
DataTrackExample.xcodeproj/project.pbxproj
ObjCVideoQuickstart.xcodeproj/project.pbxproj
ReplayKitExample.xcodeproj/project.pbxproj
ScreenCapturerExample.xcodeproj/project.pbxproj
VideoCallKitQuickStart.xcodeproj/project.pbxproj
VideoQuickStart.xcodeproj/project.pbxproj

- Increment version to 4.6.0 using `bump_spm_version.sh`.
- Did not change project files, they were properly configured. (Setting  `ONLY_ACTIVE_ARCH = YES` for debug builds is valid and saves time).

VIDEO-6636: Consume video-ios-4.6.0

---

AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m

When we restart the record and playout engine with the music file the context was not valid. So passing the valid device context during start capture and start rendering. 

VIDEO-4533

---

AudioDeviceExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m

1. Fixed a crash when the second participant joins the room and capture context is not established.

VIDEO-5099 Crash fix when second participant joins

---

ARKitExample.xcodeproj/project.pbxproj
AVPlayerExample.xcodeproj/project.pbxproj
AudioDeviceExample.xcodeproj/project.pbxproj
AudioSinkExample.xcodeproj/project.pbxproj
DataTrackExample.xcodeproj/project.pbxproj
ObjCVideoQuickstart.xcodeproj/project.pbxproj
README.md
ReplayKitExample.xcodeproj/project.pbxproj
ScreenCapturerExample.xcodeproj/project.pbxproj
VideoCallKitQuickStart.xcodeproj/project.pbxproj
VideoQuickStart.xcodeproj/project.pbxproj

Maintenance
- The minimum iOS version supported is 12.2.
- This release is built with Xcode 13.
Enhancements
- Microphone access will only be requested when recording audio and publishing an audio track.
Notes
- Starting with iOS 14.5, apps can overwrite the audio interruption caused by smart cover use on iPads. See [#225](https://github.com/twilio/twilio-video-ios/issues/225) for more details.
Bug Fixes
- Fixed a bug which could occur when connected to a Peer-to-Peer or Go Room and publishing a second video track before another Participant joins, causing the connection to be terminated or the second video track not to be fully established.
- Fixed a bug which could cause the Room connection to be terminated by the server.
- Fixed a bug which could cause the media connection not to be …

Update Twilio Video SDK package to 5.0.0

---

AudioDeviceExample/ViewController.swift
AudioSinkExample/ViewController.swift
ObjCVideoQuickstart/ViewController.m
ReplayKitExample/BroadcastExtension/SampleHandler.swift
ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift
ReplayKitExample/ReplayKitExample/ViewController.swift
Utils/Settings.swift
Utils/SettingsTableViewController.swift
VideoCallKitQuickStart/ViewController+CallKit.swift
VideoQuickStart/ViewController.swift

Features
- This release introduces Adaptive Simulcast along with new Video Encoding modes for publishers. Adaptive Simulcast reduces publisher resource usage by only sending those encodings for a video track that are needed by subscribers or by the media server (when recording is enabled). This is an opt-in feature and can be enabled by setting the new Connect Option `videoEncodingMode` to `auto`, which allows the SDK to select video codecs, use adaptive simulcast and manage encodings automatically.
API Changes
- Added the `videoEncodingMode` property to `ConnectOptions`. 
- The `videoEncodingMode` API is mutually exclusive with existing codec management APIs `EncodingParameters.maxVideoBitrate` and `preferredVideoCodecs`.
Known Issues
- Audio playback fails in some cases when running a …

Update TwilioVideo SDK to 5.1

---

ARKitExample.xcodeproj/project.pbxproj
AVPlayerExample.xcodeproj/project.pbxproj
AudioDeviceExample.xcodeproj/project.pbxproj
AudioSinkExample.xcodeproj/project.pbxproj
DataTrackExample.xcodeproj/project.pbxproj
ObjCVideoQuickstart.xcodeproj/project.pbxproj
ReplayKitExample.xcodeproj/project.pbxproj
ScreenCapturerExample.xcodeproj/project.pbxproj
VideoCallKitQuickStart.xcodeproj/project.pbxproj
VideoQuickStart.xcodeproj/project.pbxproj
VideoQuickStart/Assets.xcassets/AppIcon.appiconset/Contents.json

Bug Fixes
- Max video bandwidth limits are now applied to each simulcast layer when simulcast is enabled, and the expected behavior for max video bitrates with simulcast is better documented.
- Fixed several bugs that could cause crashes and deadlocks when a Room is disconnected / destroyed.
- Fixed a use-after-free bug associated with tasks posted to TaskQueue that could lead to undefined behavior.
- Fixed a bug which could cause a crash in IceConnectionActivityMonitor when reconnecting to or disconnecting from a Room.
- Fixed a race condition where subscribed callbacks for Remote Participant could be raised for tracks that have been ended.
Known Issues
- Audio playback fails in some cases when running a simulator on a Mac Mini. …

VIDEO-XXXX update to 5.2.0

---

VideoCallKitQuickStart/ViewController.swift
VideoQuickStart/ViewController.swift

This was a source of a bug for our app following this same convention where if we used a capital C for the camera name the remote participant could not see our camera.  I followed some similar post from previous issues on and this led me to this change.  After this change was made the remote could see our camera and everything worked. 
- [x ] I acknowledge that all my contributions will be made under the project's license.

Change C to c in camera name. 

---

ARKitExample.xcodeproj/project.pbxproj
AVPlayerExample.xcodeproj/project.pbxproj
AudioDeviceExample.xcodeproj/project.pbxproj
AudioSinkExample.xcodeproj/project.pbxproj
DataTrackExample.xcodeproj/project.pbxproj
ObjCVideoQuickstart.xcodeproj/project.pbxproj
ReplayKitExample.xcodeproj/project.pbxproj
ReplayKitExample/BroadcastExtension/ExampleReplayKitAudioCapturer.m
ScreenCapturerExample.xcodeproj/project.pbxproj
Utils/Settings.swift
VideoCallKitQuickStart.xcodeproj/project.pbxproj
VideoQuickStart.xcodeproj/project.pbxproj

Enhancements
- This version contains 'VideoTrackStoringSampleBufferVideoView' class which simplifies the implementation of Picture in Picture.
- This release is based on Chromium WebRTC 112.
- iSAC Codec is no longer supported.
Known Issues
- Audio playback fails in some cases when running a simulator on a Mac Mini. [#182](https://github.com/twilio/twilio-video-ios/issues/182)
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. [#34](https://github.com/twilio/twilio-video-ios/issues/34)
- H.264 video might become corrupted after a network handoff. [#147](https://github.com/twilio/twilio-video-ios/issues/147)
- iOS devices do not support more than three H.264 encoders. Refer to …

Update Video iOS SDK to 5.8.0

---

ARKitExample.xcodeproj/project.pbxproj
AVPlayerExample.xcodeproj/project.pbxproj
AudioDeviceExample.xcodeproj/project.pbxproj
AudioSinkExample.xcodeproj/project.pbxproj
DataTrackExample.xcodeproj/project.pbxproj
ObjCVideoQuickstart.xcodeproj/project.pbxproj
ReplayKitExample.xcodeproj/project.pbxproj
ScreenCapturerExample.xcodeproj/project.pbxproj
VideoCallKitQuickStart.xcodeproj/project.pbxproj
VideoQuickStart.xcodeproj/project.pbxproj

* Programmable Video iOS SDK 5.8.2 [[XCFramework]](https://github.com/twilio/twilio-video-ios/releases/download/5.8.2/TwilioVideo.xcframework.zip) (checksum: XCFRAMEWORK_CHECKSUM).
Enhancements
- The Privacy Manifest is updated since the SDK does not collect API usage or call quality data for tracking purposes according to [Apple's documentation](https://developer.apple.com/app-store/user-privacy-and-data-use/).
Known Issues
- Audio playback fails in some cases when running a simulator on a Mac Mini. [#182](https://github.com/twilio/twilio-video-ios/issues/182)
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. [#34](https://github.com/twilio/twilio-video-ios/issues/34)
- H.264 video might become corrupted after a network handoff. …

Update Video iOS SDK to 5.8.2

---

AudioDeviceExample/ViewController.swift
AudioSinkExample/ViewController.swift

Fixed a crash when the preview bounds were NaN because the camera permission is still not granted or denied.

VBLOCKS-4046 fix layout subview crash

---

.gitignore
ARKitExample.xcodeproj/project.pbxproj
AVPlayerExample.xcodeproj/project.pbxproj
AudioDeviceExample.xcodeproj/project.pbxproj
AudioSinkExample.xcodeproj/project.pbxproj
DataTrackExample.xcodeproj/project.pbxproj
ObjCVideoQuickstart.xcodeproj/project.pbxproj
ReplayKitExample.xcodeproj/project.pbxproj
ScreenCapturerExample.xcodeproj/project.pbxproj
VideoCallKitQuickStart.xcodeproj/project.pbxproj
VideoQuickStart.xcodeproj/project.pbxproj
VideoQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved

Enhancements
- This release is based on Chromium WebRTC 124.
- The `NoiseCancellationProcessor` audio device was updated to use Krisp 7.0.1
- The internal default audio device is now created and destroyed on the correct thread.
Known Issues
- Audio playback fails in some cases when running a simulator on a Mac Mini. [#182](https://github.com/twilio/twilio-video-ios/issues/182)
- Unpublishing and republishing a `LocalAudioTrack` or `LocalVideoTrack` might not be seen by Participants. [#34](https://github.com/twilio/twilio-video-ios/issues/34)
- H.264 video might become corrupted after a network handoff. [#147](https://github.com/twilio/twilio-video-ios/issues/147)
- iOS devices do not support more than three H.264 encoders. Refer to …

Update Video iOS SDK to 5.9.0
