- VideoQuickStart/Base.lproj/Main.storyboard
- VideoQuickStart/ViewController.swift
There is one line missing from the file in the invite function where you get the conversation back from the invite, but the conversation delegate is never set and so the participant delegate never sets the remote video view.
There were also a few problems with the constraints. I adjusted the constraints for the local video view, identity label, and hangup button so they will stay in the position regardless of screen size and this also removed the constraint errors in IB.
> Remote video view never showing.

- Podfile
Use pod spec from Github repo.
This PR has dependency on following PR - 
twilio/cocoapod-specs#1
> Podfile updated to use pod spec from github

- VideoQuickStart/ViewController.swift
> Fix preview

- Podfile
> TwilioConversationsClient 0.24.0

- VideoQuickStart/ViewController.swift
* Comments, pragma marks and code organization
* Rename toggleView to be more descriptive
* Log the participant when joining a Room
* Fix adding audio multiple times
> Update for consistency with Objective-C sample

- CustomScreenCapturerExample.xcodeproj/project.pbxproj
- CustomScreenCapturerExample/AppDelegate.swift
- CustomScreenCapturerExample/Assets.xcassets/AppIcon.appiconset/Contents.json
- CustomScreenCapturerExample/Base.lproj/LaunchScreen.storyboard
- CustomScreenCapturerExample/Base.lproj/Main.storyboard
- CustomScreenCapturerExample/ExampleScreenCapturer.swift
- CustomScreenCapturerExample/Info.plist
- CustomScreenCapturerExample/ViewController.swift
- Podfile
- README.md
Added a screen capturer example project, consume 1.0.0-beta3
> Add screen capturer example, bump to beta3

- CustomScreenCapturerExample/ExampleScreenCapturer.swift
- Podfile
* Pull in beta4 in the Podfile
* Update timestamp units to use microseconds
> Updates for 1.0.0-beta4

- Podfile
Using TwilioVideo 1.0.0-beta10
> 1.0.0-beta10

- Podfile
- ScreenCapturerExample/ViewController.swift
- VideoCallKitQuickStart/ViewController+CallKit.swift
- VideoCallKitQuickStart/ViewController.swift
- VideoQuickStart/ViewController.swift
This PR is in preparation for Beta 15.
Also fixed a couple of missing `AVFoundation` imports.
> Updated for Beta 15

- Podfile
Using TwilioVideo 1.0.0-beta16
> TwilioVideo 1.0.0-beta16

- Podfile
No code level changes were made, as we still need to add sample code which uses TVIAudioSink.
> Consume Twilio Video 1.2.x.

- ScreenCapturerExample/ExampleScreenCapturer.swift
The format should reflect what we are actually capturing in.
> Use BGRA for the ExampleScreenCapturer format as well.

- Podfile
- ScreenCapturerExample/ExampleScreenCapturer.swift
- VideoCallKitQuickStart/ViewController.swift
- VideoQuickStart/ViewController.swift
Support for 2.0.0-preview1 on a branch separate from master. Updates the sample code to be compatible with 2.0 APIs.
> Add 2.0.0-preview branch

- Podfile
- README.md
There are no breaking API changes in this release, only bug fixes.
> Consume 2.0.0-preview2.

- README.md
Trying to prevent issues like: https://github.com/twilio/video-quickstart-swift/issues/169
> Cross link from master to 2.0.0-preview branch in README.md.

- Utils/Settings.swift
- Utils/SettingsTableViewController.swift
- VideoCallKitQuickStart/ViewController+CallKit.swift
- VideoQuickStart/ViewController.swift
- Added Encoding params in settings tableview controller.
- The encoding params are passed to connect options while connecting to a Room
> Added Encoding params in settings tableview controller

- ARKitExample/ViewController.swift
Bring this improvement back to master.
> Make displayLink handler more idiomatic Swift.

- ARKitExample/README.md
Doesn't look like any character changed at the bottom. Content is the same.
> Add link to blog

- ARKitExample/ViewController.swift
- VideoCallKitQuickStart/ViewController.swift
- VideoQuickStart/Utils.swift
- VideoQuickStart/ViewController.swift
Bring these changes back to master.
* Update console token link comments
* Make TokenUtils compatible with latest devEd servers.
> Access token generation updates.

- .github/ISSUE_TEMPLATE.md
Update our issue template to reference twilio-video-ios for SDK level requests. If we agree on this format, I'll submit a small PR to twilio-video-ios which brings its template in line with the change.
> ISDK-1913: Update issue template to redirect to twilio-video-ios.

- Utils/Settings.swift
- Utils/SettingsTableViewController.swift
Added settings to chose VP8 Simulcast while connecting to a Room - 
----
<kbd><img width="400px" src="https://user-images.githubusercontent.com/17037593/40691834-0fcd75b6-6363-11e8-9203-ed7826119896.PNG"/></kbd>
----
<kbd><img width="400px" src="https://user-images.githubusercontent.com/17037593/40691835-0fe7d212-6363-11e8-8e2e-1b6295ae846a.PNG"/></kbd>
> ISDK-1893 Settings to enable VP8 Simulcast while connecting to a Room

- README.md
- Update download, getting started links.
- Reference 2.3.0-preview branch.
> README.md: Update docs and branch links.

- AudioSinkExample/AudioSinks/ExampleAudioRecorder.m
- AudioSinkExample/AudioSinks/ExampleSpeechRecognizer.m
- AudioSinkExample/README.md
This PR improves AudioSinkExample, making the sinks more adaptable to different channel and sample rate configurations. This work was a initially done as part of test and internal app betterments for twilio-video-ios.
1. Refactor ExampleSpeechRecognizer to be channel agnostic.
2. ExampleAudioRecorder dynamically determines formats.
* Wait for the first valid audio sample.
* Create AVAssetWriter/Input on demand with the correct channels and sample rate.
3. Mention ExampleAudioRecorder silence detection in the known issues section of README.md.
> ISDK-2091: Improve AudioSinkExample (2.3.0-preview)

- Podfile
> Using TwilioVideo 2.5.0

- README.md
- ScreenCapturerExample/README.md
* Keep 1.x reference, remove 2.6.0-preview reference.
* Typo fix for screen capturer.
> Update the readme to no longer reference 2.6.0-preview.

- ReplayKitExample/BroadcastExtension/SampleHandler.swift
- ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift
- ReplayKitExample/ReplayKitExample/ViewController.swift
* Make format request logic reusable
* ViewController also makes a format request
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
> ISDK-2512: Conference mode with downscaling should downscale buffers.

- README.md
> Crosslink 3.0.0 beta branch

- Podfile
- README.md
Updates Quickstarts for `3.0.0-beta3`
> Updated for beta 3

- Podfile
- README.md
Update podfile & README.md for 3.0.0-beta4.
> Updates for 3.0.0-beta4

- ReplayKitExample/README.md
Same as https://github.com/twilio/video-quickstart-ios/pull/424 but on master.
> Confirm ReplayKit bugs on iOS 13.0 GM. (master)

- ARKitExample/README.md
- AVPlayerExample/README.md
- AudioDeviceExample/README.md
- AudioSinkExample/README.md
- DataTrackExample/README.md
- MultiPartyExample/README.md
- README.md
- ReplayKitExample/README.md
In preparation for the 3.0 release, a `2.x` branch was created from the current `master` branch. This PR updates the `2.x` branch with references from `master` to `2.x`.
> ISDK-2603: Update README’s for the 2.x branch.

- ARKitExample/README.md
- AudioDeviceExample/README.md
- AudioSinkExample/README.md
- Cartfile
- MultiPartyExample/README.md
- Podfile
- README.md
- ReplayKitExample/README.md
Updates the links for the 3.0 GA. Once this PR is merged to this branch, the `3.0.0-beta` branch can be merged to `master`.
> ISDK-2603: Link updates for 3.0 GA

- Cartfile
- MultiPartyExample/MultiPartyViewController.swift
- Podfile
Update the Podfile to require 3.1.0, and update MultipartyExample to demonstrate the rotation tag removal API.
> Releasing 3.1.0

- README.md
Add video app link to readme like https://github.com/twilio/video-quickstart-js.
> AHOYAPPS-477: Add video app link to readme

- Cartfile
- Podfile
Update Podfile and Cartfile to use the latest minor release.
> Consume video-ios-3.3.0.

- Cartfile
- Podfile
Bump the Cartfile and Podfile for the 3.5.0 release. We weren't using the deprecated TVIIceOptions APIs, so I have not made any changes to the source.
> Update for the video-ios-3.5.0 release.

- README.md
Updates the README.md to link to the iOS 14 issue ~and remove the link to iOS 13~.
> ISDK-2952: Add README.md header for iOS 14 tracker issue.

- Podfile
- VideoCallKitQuickStart/ViewController.swift
> Consume TwilioVideo 3.6.0

- Cartfile
- Podfile
> Use TwilioVideoSDK 3.7.0+ 

- Podfile
> Update for 2.11.0 Release

- VideoCallKitQuickStart/ViewController+CallKit.swift
> CallKit integration with 4.0.0-beta1

- ARKitExample.xcodeproj/project.pbxproj
- AVPlayerExample.xcodeproj/project.pbxproj
- AudioDeviceExample.xcodeproj/project.pbxproj
- AudioSinkExample.xcodeproj/project.pbxproj
- DataTrackExample.xcodeproj/project.pbxproj
- ObjCVideoQuickstart.xcodeproj/project.pbxproj
- README.md
- ReplayKitExample.xcodeproj/project.pbxproj
- ScreenCapturerExample.xcodeproj/project.pbxproj
- VideoCallKitQuickStart.xcodeproj/project.pbxproj
- VideoQuickStart.xcodeproj/project.pbxproj
- VideoQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Use beta-2

- README.md
Add text about the requirement for Client-side Room Creation enabled.
Also updated the doc link to the currently published beta.
> ISDK-3059: Add text about the requirement for Client-side Room Creation enabled.

- ARKitExample/README.md
- AVPlayerExample/README.md
- AudioDeviceExample/README.md
- AudioSinkExample/README.md
- DataTrackExample/README.md
- README.md
- ReplayKitExample/README.md
In preparation for the `4.0.0` release, the `3.x` branch was created from the current `master` branch. This PR updates all the links appropriately.
> Update 3.x branch with proper doc links

- Cartfile
- Podfile
Updated dependency files for Cocoapods and Carthage.
> Updated for iOS 3.8.0

- ARKitExample.xcodeproj/project.pbxproj
- AVPlayerExample.xcodeproj/project.pbxproj
- AudioDeviceExample.xcodeproj/project.pbxproj
- AudioSinkExample.xcodeproj/project.pbxproj
- DataTrackExample.xcodeproj/project.pbxproj
- ObjCVideoQuickstart.xcodeproj/project.pbxproj
- README.md
- ReplayKitExample.xcodeproj/project.pbxproj
- ScreenCapturerExample.xcodeproj/project.pbxproj
- VideoCallKitQuickStart.xcodeproj/project.pbxproj
- VideoQuickStart.xcodeproj/project.pbxproj
This PR updates the Quickstarts to use Twilio Video iOS `4.2.0`.
> Updated for 4.2.0

- ARKitExample.xcodeproj/project.pbxproj
- AVPlayerExample.xcodeproj/project.pbxproj
- AudioDeviceExample.xcodeproj/project.pbxproj
- AudioSinkExample.xcodeproj/project.pbxproj
- DataTrackExample.xcodeproj/project.pbxproj
- ObjCVideoQuickstart.xcodeproj/project.pbxproj
- ReplayKitExample.xcodeproj/project.pbxproj
- ScreenCapturerExample.xcodeproj/project.pbxproj
- VideoCallKitQuickStart.xcodeproj/project.pbxproj
- VideoQuickStart.xcodeproj/project.pbxproj
- bump_spm_version.sh
Consume Twilio Video iOS 4.3.0
> Consume Video iOS 4.3.0

- ARKitExample.xcodeproj/project.pbxproj
- AVPlayerExample.xcodeproj/project.pbxproj
- AudioDeviceExample.xcodeproj/project.pbxproj
- AudioSinkExample.xcodeproj/project.pbxproj
- DataTrackExample.xcodeproj/project.pbxproj
- ObjCVideoQuickstart.xcodeproj/project.pbxproj
- ReplayKitExample.xcodeproj/project.pbxproj
- ScreenCapturerExample.xcodeproj/project.pbxproj
- VideoCallKitQuickStart.xcodeproj/project.pbxproj
- VideoQuickStart.xcodeproj/project.pbxproj
Updated to consume Video iOS 4.4.0
> Updated for Video iOS 4.4.0

- ARKitExample.xcodeproj/project.pbxproj
- AVPlayerExample.xcodeproj/project.pbxproj
- AudioDeviceExample.xcodeproj/project.pbxproj
- AudioSinkExample.xcodeproj/project.pbxproj
- DataTrackExample.xcodeproj/project.pbxproj
- ObjCVideoQuickstart.xcodeproj/project.pbxproj
- README.md
- ReplayKitExample.xcodeproj/project.pbxproj
- ScreenCapturerExample.xcodeproj/project.pbxproj
- VideoCallKitQuickStart.xcodeproj/project.pbxproj
- VideoQuickStart.xcodeproj/project.pbxproj
Updated the project to consume the `4.6.0-beta1` release.
> Updated to consume 4.6.0-beta1

- AudioDeviceExample/ViewController.swift
- AudioSinkExample/ViewController.swift
- DataTrackExample/ViewController.swift
- ReplayKitExample/BroadcastExtension/SampleHandler.swift
- ReplayKitExample/ReplayKitExample/ViewController.swift
- Utils/Utils.swift
- VideoCallKitQuickStart/ViewController+CallKit.swift
- VideoCallKitQuickStart/ViewController.swift
- VideoQuickStart/Base.lproj/Main.storyboard
- VideoQuickStart/ViewController.swift
1. The utils method for access token fetching was happening on main thread. This network request was blocking the main thread so made that method asynchronous by using URLSession.
2. fixed the constraint issue for the video quick start example.
3. All the changes are tested locally on physical device.
> VIDEO- 6817 Fix app freeze issue for swift applications

- AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.h
- AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m
- AudioDeviceExample/AudioDevices/ExampleCoreAudioDevice.m
Bring improvements from Video SDK's Krisp audio device to the AVAudioEngineDevice.
> VIDEO-12596: Bring improvements from Krisp audio device to AVAudioEngineDevice

- README.md
> VBLOCKS-3586- Removed EOL banner

- ARKitExample.xcodeproj/project.pbxproj
- AVPlayerExample.xcodeproj/project.pbxproj
- AudioDeviceExample.xcodeproj/project.pbxproj
- AudioSinkExample.xcodeproj/project.pbxproj
- DataTrackExample.xcodeproj/project.pbxproj
- ObjCVideoQuickstart.xcodeproj/project.pbxproj
- ReplayKitExample.xcodeproj/project.pbxproj
- ScreenCapturerExample.xcodeproj/project.pbxproj
- VideoCallKitQuickStart.xcodeproj/project.pbxproj
- VideoQuickStart.xcodeproj/project.pbxproj
- VideoQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
> VBLOCKS-5409 update to 5.10.2
